### ISSUE TITLE
Unexpected backslashes in nodes' name

### ISSUE THREAD

**Issue by XXLeeS** [christophergandrud/networkD3#140] opened 2016-07-20 19:08 UTC
I set the nodes' name in Chinese, but some of the name was inserted '\' unexpected in the saved html file.
Like the screenshot below.
http://imgur.com/a/D1Cfj
My package version is the latest 0.2.12.
Thanks for replying and sorry for my poor English.

**Comment by christophergandrud** [comment] 2016-07-22 05:44
Hu, I'm a little stumped on this one. From your screen shot it looks like the backslashes are before 大. Can you think of any reason for this pattern?

**Comment by timelyportfolio** [comment] 2016-07-22 16:26
Not sure, but there has been some recent work by @yihui on `rmarkdown` \ `htmltools` regarding Chinese encoding.  Potentially related to https://github.com/rstudio/rmarkdown/issues/748.

**Comment by yihui** [comment] 2016-07-22 19:09
I don't think my work was relevant to this issue. I have never seen this problem before. A minimal reproducible with `devtools::session_info()` may be helpful to debug the problem.

**Comment by XXLeeS** [comment] 2016-07-23 07:30
I found that all of the backslashes are appear after some specific Chinese characters, not before.
Here is all the word with problem in my file.
功\
璞\
餐\
The names go uncontrolled after I sent the data.frame to the forceNetwork function.
Here is the Nodes data.frame.
http://imgur.com/a/6kRha

And here is my session_info()
Session info ----------------------------------------------------------------------
 setting  value                           
 version  R version 3.2.5 (2016-04-14)    
 system   x86_64, mingw32                 
 ui       RStudio (0.99.879)              
 language (EN)                            
 collate  Chinese (Traditional)_Taiwan.950
 tz       Asia/Taipei                     
 date     2016-07-23 

Thanks for helping!

**Comment by cjyetman** [comment] 2017-03-16 10:41
Please test this with the newest release version (currently 0.3). I'm going to close this because it's practically impossible to deal with this issue without a reproducible example. If you can provide a [minimal reproducible example](http://stackoverflow.com/a/5963610/4389763) that still demonstrates this issue using the latest release of networkD3, then we will reopen.

**Closed by cjyetman** 2017-03-16 10:41 UTC
