### ISSUE TITLE
Rectangular nodes and manhattan routing

### ISSUE THREAD

**Issue by trollas** [christophergandrud/networkD3#124] opened 2016-05-19 06:50 UTC
Hi.
Would it be possible to change nodes from circles to rectangles instead?
This could be an option along with other shapes.
Alternatives to direct connections, such as manhattan routing would be great. See this example: http://jointjs.com/demos/routing

**Comment by christophergandrud** [comment] 2016-07-10 06:34
I'ld definitely consider a pull request.

**Comment by cjyetman** [comment] 2017-02-21 16:08
is this related to force network plots, or hierarchical network plots?

**Comment by cjyetman** [comment] 2017-03-18 09:40
closing this as a duplicate of #12 for nodeSize and nodeShape feature request

in regards to "manhattan routing", I think this is already roughly achieved with the `linkType = c("elbow", "diagonal")` argument in the `dendroNetwork()` function, and will soon be available to the `diagonalNetwork()` and `radialNetwork()` functions once we merge all of their code bases into one `treeNetwork()` function as in #171

**Closed by cjyetman** 2017-03-18 09:40 UTC
Labels: treeNetwork
