### ISSUE TITLE
Feature req: force network chart to display chronologically

### ISSUE THREAD

**Issue by mexindian** [christophergandrud/networkD3#104] opened 2016-01-25 10:53 UTC
I have found a network chart that displays chronologically depending on user clicks. https://www.hooktheory.com/trends#node=4.5.6&key=C

This allows for a controlled and detailed investigation of a network chart by hierarchy. Would something like this be possible using this package from R?

**Comment by cjyetman** [comment] 2017-02-21 16:15
I'm not sure I understand what's happening in that example. I can imagine only showing connected nodes and links on click, similar to the suggestions in #168 and #137. Is that what you're interested in?

**Comment by mexindian** [comment] 2017-02-22 09:19
Yes, exactly. I feel like the trick is in having some kind of "visibility" feature on the node set.... that way by default I could say "keep these nodes visible but these ones hidden", and then clicking on peripheral nodes would change the visibility of all connected nodes to visible, then toggle all false.

Possible?

**Comment by cjyetman** [comment] 2017-02-22 09:45
take a look at [focus on connected links and nodes on hover #168](https://github.com/christophergandrud/networkD3/issues/168)

it will focus on connected nodes and links on hover, but not click. if that's a suitable alternative to what you're asking for here, let's close this issue as a duplicate

**Comment by mexindian** [comment] 2017-02-22 11:28
I could install the dev version... It's not particularly the same thing as #168, but it is the same as #137. So yes, mark as duplicate of that.

**Comment by cjyetman** [comment] 2017-02-22 12:06
thanks.... closed as duplicate of #137

**Closed by cjyetman** 2017-02-22 12:06 UTC
Labels: forceNetwork
