### ISSUE TITLE
graph too (big) zoomed in

### ISSUE THREAD

**Issue by pajosean** [christophergandrud/networkD3#196] opened 2017-05-11 06:54 UTC
Hi
As you can see my graph expands way too much and i can't find a way to stop this.
https://pajosean.shinyapps.io/autoresc3/
I want to be able to see it all at once or at least to zoom out
[app.txt](https://github.com/christophergandrud/networkD3/files/992059/app.txt)

Please help! Thanks!

**Comment by cjyetman** [comment] 2017-05-11 10:35
I can zoom in and out on your shiny app. It looks like you have a very high `linkDistance` or a very low (negative) `charge`, but I don't see that in the code you posted. Are you sure it's the same?

You can help us help you if you create a [minimal reproducible example](http://adv-r.had.co.nz/Reproducibility.html), including the data, so that we can run it ourselves.

**Comment by pajosean** [comment] 2017-05-15 17:13
Could you please point out how to zoom out?
I'll send you the data, but i'm thinking the whole problem is that i don't know how to zoom out... Ha, sorry

**Comment by cjyetman** [comment] 2017-05-15 17:21
Scroll wheel on a mouse, dragging two fingers up or down on a trackpad, pinch on a touchscreen? Somewhat depends on your system and its settings.

**Comment by cjyetman** [comment] 2017-05-23 12:29
I assume this is not a bug... closing issue

**Closed by cjyetman** 2017-05-23 12:29 UTC
Labels: question

**Comment by pajosean** [comment] 2017-05-23 19:22
Yes. Sorry i didn't answer back! My machine couldn't do it, but we could
solve it in others.
Thank you very much
Best
